// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc9KI0KIQhjvqpxLXzTFbTP7NETnaEzPg',
    appId: '1:830384608051:web:ca6173970cadeb588a2446',
    messagingSenderId: '830384608051',
    projectId: 'stareducation-bb821',
    authDomain: 'stareducation-bb821.firebaseapp.com',
    storageBucket: 'stareducation-bb821.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtdtK6v-hLOWVcG-PtPozvDWuuBHTTXaU',
    appId: '1:830384608051:android:2fa2d7222045fc1b8a2446',
    messagingSenderId: '830384608051',
    projectId: 'stareducation-bb821',
    storageBucket: 'stareducation-bb821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXPHgo5Ro4dWOtBtophEq4X9KEr1LuE40',
    appId: '1:830384608051:ios:ec6d87aef383c4808a2446',
    messagingSenderId: '830384608051',
    projectId: 'stareducation-bb821',
    storageBucket: 'stareducation-bb821.appspot.com',
    iosBundleId: 'com.example.stareducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXPHgo5Ro4dWOtBtophEq4X9KEr1LuE40',
    appId: '1:830384608051:ios:ec6d87aef383c4808a2446',
    messagingSenderId: '830384608051',
    projectId: 'stareducation-bb821',
    storageBucket: 'stareducation-bb821.appspot.com',
    iosBundleId: 'com.example.stareducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc9KI0KIQhjvqpxLXzTFbTP7NETnaEzPg',
    appId: '1:830384608051:web:4c6eff7f548958b48a2446',
    messagingSenderId: '830384608051',
    projectId: 'stareducation-bb821',
    authDomain: 'stareducation-bb821.firebaseapp.com',
    storageBucket: 'stareducation-bb821.appspot.com',
  );
}



